# Generated by Django 4.0.3 on 2022-05-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pickle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickle_name', models.CharField(max_length=30)),
                ('pickle_ingredients', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
